export const questions = [
  // ------------------------------------------------------
  // STEM (15 questions per difficulty)
  // EASY
  { question: "What is the square root of 144?", 
    options: ["10", "12", "14", "16"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "What planet is known as the Red Planet?", 
    options: ["Mars", "Venus", "Jupiter", "Saturn"], 
    correctIndex: 0, category: "stem", difficulty: "easy" },
  { question: "What is H2O commonly known as?", 
    options: ["Hydrogen Peroxide", "Water", "Oxygen", "Salt"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "Which number is a prime number?", 
    options: ["15", "21", "17", "27"], 
    correctIndex: 2, category: "stem", difficulty: "easy" },
  { question: "What is the chemical symbol for gold?", 
    options: ["Au", "Ag", "Gd", "Go"], 
    correctIndex: 0, category: "stem", difficulty: "easy" },
  { question: "What is 0! (zero factorial)?", 
    options: ["0", "1", "Undefined", "Infinity"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "Which gas do plants absorb from the atmosphere?", 
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "What force keeps planets in orbit around the sun?", 
    options: ["Magnetism", "Gravity", "Friction", "Centrifugal"], 
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "Who developed the theory of relativity?", 
    options: ["Newton", "Tesla", "Einstein", "Galileo"], 
    correctIndex: 2, category: "stem", difficulty: "easy" },
  { question: "How many sides does a hexagon have?",
    options: ["5", "6", "7", "8"],
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "How many planets are in our solar system?",
    options: ["7", "8", "9", "10"],
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "What is the center of an atom called?",
    options: ["Electron", "Nucleus", "Proton", "Liver"],
    correctIndex: 1, category: "stem", difficulty: "easy" },
  { question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Cytoplasm", "Cell Membrane", "Mitochondria"],
    correctIndex: 3, category: "stem", difficulty: "easy" },
  { question: "What is the largest planet in our solar system?",
    options: ["Jupiter", "Uranus", "Saturn", "Pluto"],
    correctIndex: 0, category: "stem", difficulty: "easy" },
  { question: "How many degrees are in a right angle?",
    options: ["30", "50", "80", "90"],
    correctIndex: 3, category: "stem", difficulty: "easy" },

  // MEDIUM
  { question: "How many bones are in the human body?", 
    options: [ "210","206", "195", "220"], 
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "Which data structure follows FIFO?",
    options: ["Stack", "Queue", "Tree", "Graph"],
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "The process of converting sensitive or complex data into smaller, manageable, or non-sensitive units is called?", 
    options: ["Encryption", "Tokenization", "Hashing", "Anonymization"], 
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "Which organ in the human body produces insulin?", 
    options: ["Liver", "Pancreas", "Kidney", "Stomach"], 
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "Which programming language is known for its use in data science and machine learning?", 
    options: ["Java", "C++", "Python", "Ruby"], 
    correctIndex: 2, category: "stem", difficulty: "medium" },
  { question: "What is the chemical formula for table salt?", 
    options: ["NaCl", "KCl", "NaHCO3", "CaCl2"], 
    correctIndex: 0, category: "stem", difficulty: "medium" },
  { question: "What is Amazon's cloud computing platform called?", 
    options: ["AWS", "Google Cloud", "Azure", "IBM Cloud"], 
    correctIndex: 0, category: "stem", difficulty: "medium" },
  { question: "What does HTTP stand for?",
    options: ["High Tech Transfer Process", "Hyper Transfer Text Program", "Host Text Transfer Protocol", "HyperText Transfer Protocol"],
    correctIndex: 3, category: "stem", difficulty: "medium" },
  { question: "In what base does a binary number system operate?",
    options: ["Base 8", "Base 10", "Base 2", "Base 16"],
    correctIndex: 2, category: "stem", difficulty: "medium" },
  { question: "What is the most abundant gas in the universe?",
    options: ["Hydrogen", "Nitrogen", "Oxygen", "Helium"],
    correctIndex: 0, category: "stem", difficulty: "medium" },
  { question: "What part of the human body is primarily responsible for filtering blood?",
    options: ["Liver", "Kidneys", "Heart", "Veins"],
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "What is the term for a substance with a pH less than 7?",
    options: ["Dry", "Neutral", "Acidic", "Alkaline"],
    correctIndex: 2, category: "stem", difficulty: "medium" },
  { question: "Who is known as the first computer programmer?",
    options: ["Ada Lovelace", "Bill Gates", "Konrad Zuse", "Charles Babbage"],
    correctIndex: 0, category: "stem", difficulty: "medium" },
  { question: "What is the next number in the Fibonacci sequence: 1, 1, 2, 3, 5, 8, __?",
    options: ["11", "13", "15", "18"],
    correctIndex: 1, category: "stem", difficulty: "medium" },
  { question: "What is the pH of water?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2, category: "stem", difficulty: "medium" },

  // HARD
  { question: "What is the smallest element on the periodic table by atomic number?", 
    options: ["Natrium", "Lithium", "Beryllium", "Hydrogen"], 
    correctIndex: 3, category: "stem", difficulty: "hard" },
  { question: "Researchers from which company helped develop the first successful quantum computer?",
    options: ["Google", "Salesforce", "D-Wave", "IBM"], 
    correctIndex: 3, category: "stem", difficulty: "hard" },
  { question: "What is Microsoft's analytics platform called?", 
    options: ["Fabric", "Tableau", "Azure", "Office 365"], 
    correctIndex: 0, category: "stem", difficulty: "hard" },
  { question: "What is the only metal that is liquid at room temperature?", 
    options: ["Mercury", "Iron", "Titanium", "Bronze"], 
    correctIndex: 0, category: "stem", difficulty: "hard" },
  { question: "What is the time complexity of binary search?",
    options: ["O(n)", "O(n²)", "O(log n)", "O(1)"],
    correctIndex: 2, category: "stem", difficulty: "hard" },
  { question: "Which protocol is used to assign IP addresses automatically on a network?",
    options: ["DNS", "FTP", "DHCP", "SSH"],
    correctIndex: 2, category: "stem", difficulty: "hard" },
  { question: "What is the atomic number of carbon?",
    options: ["4", "6", "8", "12"],
    correctIndex: 1, category: "stem", difficulty: "hard" },
  { question: "What is the name of the process by which a cell divides into two identical daughter cells?",
    options: ["Meiosis", "Mitosis", "Fission", "Budding"],
    correctIndex: 1, category: "stem", difficulty: "hard" },
  { question: "What element did Joseph Priestly discover in 1774?",
    options: ["Nitrogen", "Helium", "Argon", "Oxygen"],
    correctIndex: 3, category: "stem", difficulty: "hard" },
  { question: "At what temperature are Celsius and Fahrenheit equal?",
    options: ["-80 degrees", "-60 degrees", "-40 degrees", "-20 degrees"],
    correctIndex: 2, category: "stem", difficulty: "hard" },
  { question: "What element was named after the Greek word for greenish-yellow?",
    options: ["Chlorine", "Sulfur", "Fluorine", "Uranium"],
    correctIndex: 0, category: "stem", difficulty: "hard" },
  { question: "What letter is used to express the speed of light in E=MC^2?",
    options: ["M", "C", "E", "A"],
    correctIndex: 1, category: "stem", difficulty: "hard" },
  { question: "What type of symmetry can be found in Starfish, whose limbs radiate from one central point?",
    options: ["Radial", "Rotational", "Reflectional", "Bilateral"],
    correctIndex: 0, category: "stem", difficulty: "hard" },
  { question: "Which famous Greek mathematician is known for having accurately calculated the circumference of planet Earth using only shadows and some simple geometry?",
    options: ["Thales", "Euclid", "Eratosthenes", "Archimedes"],
    correctIndex: 2, category: "stem", difficulty: "hard" },
  { question: "Which planet has the longest day?",
    options: ["Jupiter", "Venus", "Mercury", "Pluto"],
    correctIndex: 1, category: "stem", difficulty: "hard" },


  // ------------------------------------------------------
  // Shows and Movies (15 questions per difficulty)
  // EASY
  { question: "Which movie has the quote 'May the Force be with you'?", 
    options: ["Avatar", "Star Trek", "Guardians of the Galaxy", "Star Wars"], 
    correctIndex: 3, category: "shows_movies", difficulty: "easy" },
  { question: "Which movie features the Avengers?", 
    options: ["The Avengers", "Justice League", "Inception", "The Matrix"], 
    correctIndex: 0, category: "shows_movies", difficulty: "easy" },
  { question: "Which movie features the character Elsa?", 
    options: ["Brave", "Tangled", "Frozen", "Moana"], 
    correctIndex: 2, category: "shows_movies", difficulty: "easy" },
  { question: "Which movie is part of the Marvel Cinematic Universe?", 
    options: ["Batman", "Inception", "Jurassic Park", "Iron Man"], 
    correctIndex: 3, category: "shows_movies", difficulty: "easy" },
  { question: "Which show features a coffee shop called Central Perk?", 
    options: ["Seinfeld", "How I Met Your Mother", "The Office", "Friends"], 
    correctIndex: 3, category: "shows_movies", difficulty: "easy" },
  { question: "Which movie features the song 'Let It Go'?", 
    options: ["Frozen", "Moana", "Encanto", "Tangled"], 
    correctIndex: 0, category: "shows_movies", difficulty: "easy" },
  { question: "Which movie series features characters named Woody and Buzz Lightyear?", 
    options: ["Toy Story", "Shrek", "Ice Age", "Madagascar"], 
    correctIndex: 0, category: "shows_movies", difficulty: "easy" },
  { question: "Which movie features the character Jack Sparrow?", 
    options: ["Pirates of the Caribbean", "The Mummy", "Indiana Jones", "National Treasure"], 
    correctIndex: 0, category: "shows_movies", difficulty: "easy" },
  { question: "Which show is about a chemistry teacher who becomes a drug manufacturer?", 
    options: ["Ozark", "Narcos", "Breaking Bad", "Dexter"], 
    correctIndex: 2, category: "shows_movies", difficulty: "easy" },
  { question: "What color is the Hulk?", 
    options: ["Blue", "Red", "Yellow", "Green"], 
    correctIndex: 3, category: "shows_movies", difficulty: "easy" },
  { question: "Which streaming service is known for the red envelope logo?", 
    options: ["Hulu", "Disney+", "Netflix", "HBO Max"], 
    correctIndex: 2, category: "shows_movies", difficulty: "easy" },
  { question: "In which movie does a clownfish search for his son?", 
    options: ["Shark Tale", "Finding Nemo", "The Little Mermaid", "Moana"], 
    correctIndex: 1, category: "shows_movies", difficulty: "easy" },
  { question: "Which movie is set in the African kingdom of Wakanda?", 
    options: ["Thor", "Black Panther", "Aquaman", "Captain America"], 
    correctIndex: 1, category: "shows_movies", difficulty: "easy" },
  { question: "Who is Spider-Man's alter ego?", 
    options: ["Bruce Wayne", "Clark Kent", "Peter Parker", "Barry Allen"], 
    correctIndex: 2, category: "shows_movies", difficulty: "easy" },
  { question: "What is the name of the wizard school in Harry Potter?", 
    options: ["Osthorne Academy of Young Mages", "Roke School of Wizards", "Hogwarts", "Strixhaven"], 
    correctIndex: 2, category: "shows_movies", difficulty: "easy" },

  // MEDIUM
  { question: "In the wizard of Oz, how many companions did Dorothy and Toto have by the end of their journey?", 
    options: ["1", "2", "3", "4"], 
    correctIndex: 2, category: "shows_movies", difficulty: "medium" },
  { question: "Who played the Joker in the 2019 movie?", 
    options: ["Heath Ledger", "Joaquin Phoenix", "Jack Nicholson", "Jared Leto"], 
    correctIndex: 1, category: "shows_movies", difficulty: "medium" },
  { question: "Who played Jack in Titanic?", 
    options: ["Leonardo DiCaprio", "Brad Pitt", "Tom Cruise", "Johnny Depp"], 
    correctIndex: 0, category: "shows_movies", difficulty: "medium" },
  { question: "Who played Hermione in the Harry Potter series?", 
    options: ["Natalie Portman", "Daniel Radcliffe", "Rupert Grint", "Emma Watson"], 
    correctIndex: 3, category: "shows_movies", difficulty: "medium" },
  { question: "Which animated movie features a talking snowman named Olaf?", 
    options: ["Frozen", "Moana", "Tangled", "Encanto"], 
    correctIndex: 0, category: "shows_movies", difficulty: "medium" },
  { question: "Which show is set in the fictional town of Hawkins?", 
    options: ["Riverdale", "The Umbrella Academy", "Stranger Things", "Outer Banks"], 
    correctIndex: 2, category: "shows_movies", difficulty: "medium" },
  { question: "Who voices Woody in Toy Story?", 
    options: ["Tom Hanks", "Tim Allen", "Robin Williams", "Billy Crystal"], 
    correctIndex: 0, category: "shows_movies", difficulty: "medium" },
  { question: "Which series has the characters Daenerys and Jon Snow?", 
    options: ["The Witcher", "Vikings", "Game of Thrones", "The Mandalorian"], 
    correctIndex: 2, category: "shows_movies", difficulty: "medium" },
  { question: "Which TV show has a character named Sheldon Cooper?", 
    options: ["New Girl", "The Big Bang Theory", "Modern Family", "Community"], 
    correctIndex: 1, category: "shows_movies", difficulty: "medium" },
  { question: "Which show features a character named Rick Sanchez?", 
    options: ["Rick and Morty", "Futurama", "The Simpsons", "South Park"], 
    correctIndex: 0, category: "shows_movies", difficulty: "medium" },
  { question: "Which show famously takes place in Seattle?", 
    options: ["New Girl", "The Big Bang Theory", "Friends", "Grey's Anatomy"], 
    correctIndex: 3, category: "shows_movies", difficulty: "medium" },
  { question: "Which movie features a character who is left alone on Mars?", 
    options: ["Gravity", "Interstellar", "The Martian", "Apollo 13"], 
    correctIndex: 2, category: "shows_movies", difficulty: "medium" },
  { question: "Who directed the movie Inception?", 
    options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Ridley Scott"], 
    correctIndex: 2, category: "shows_movies", difficulty: "medium" },
  { question: "Which show is set in Westeros?", 
    options: ["The Witcher", "Game of Thrones", "Vikings", "The Last Kingdom"], 
    correctIndex: 1, category: "shows_movies", difficulty: "medium" },
  { question: "Which actor played Batman in the 2022 movie The Batman?", 
    options: ["Ben Affleck", "Christian Bale", "Robert Pattinson", "Michael Keaton"], 
    correctIndex: 2, category: "shows_movies", difficulty: "medium" },

  // HARD
  { question: "What was the biggest movie in terms of box office revenue in 2023?", 
    options: ["Avatar: The Way of Water", "Wicked", "Barbie", "Oppenheimer"], 
    correctIndex: 2, category: "shows_movies", difficulty: "hard"},
  { question: "What was the biggest movie in terms of box office revenue in 2025?", 
    options: ["Zootopia 2", "Avatar: Fire and Ash", "Superman", "Wicked 2"], 
    correctIndex: 0, category: "shows_movies", difficulty: "hard" },
  { question: "In Friends, what is the name of Ross's pet monkey?", 
    options: ["Spike", "Marcel", "Bubbles", "Coco"], 
    correctIndex: 1, category: "shows_movies", difficulty: "hard" },
  { question: "Which director is known for films like Pulp Fiction and Kill Bill?", 
    options: ["Martin Scorsese", "Quentin Tarantino", "David Fincher", "Coen Brothers"], 
    correctIndex: 1, category: "shows_movies", difficulty: "hard" },
  { question: "What year was the first episode of The Simpsons aired?", 
    options: ["1987", "1988", "1989", "1990"], 
    correctIndex: 2, category: "shows_movies", difficulty: "hard" },
  { question: "Which actor has played James Bond the most times?", 
    options: ["Sean Connery", "Roger Moore", "Pierce Brosnan", "Daniel Craig"], 
    correctIndex: 1, category: "shows_movies", difficulty: "hard" },
  { question: "What is the name of the fictional language spoken by the Na'vi in Avatar?", 
    options: ["Klingon", "Dothraki", "Na'vi", "Elvish"], 
    correctIndex: 2, category: "shows_movies", difficulty: "hard" },
  { question: "In Breaking Bad, what is the street name of Walter White's blue meth?", 
    options: ["Blue Sky", "Crystal Blue", "Blue Ice", "Blueberry"], 
    correctIndex: 0, category: "shows_movies", difficulty: "hard" },
  { question: "Which film won the first ever Academy Award for Best Picture in 1928?", 
    options: ["Sunrise", "Wings", "The Jazz Singer", "Chang"], 
    correctIndex: 1, category: "shows_movies", difficulty: "hard" },
  { question: "What is the name of the prison in Orange Is the New Black?", 
    options: ["Litchfield Penitentiary", "Shawshank State Prison", "Fox River Penitentiary", "Sing Sing"], 
    correctIndex: 0, category: "shows_movies", difficulty: "hard" },
  { question: "Which movie has the longest runtime in the Lord of the Rings extended trilogy?", 
    options: ["The Fellowship of the Ring", "The Two Towers", "The Return of the King", "They are all the same"], 
    correctIndex: 2, category: "shows_movies", difficulty: "hard" },
  { question: "In The Sopranos, what is the name of Tony Soprano's psychiatrist?", 
    options: ["Dr. Katz", "Dr. Melfi", "Dr. House", "Dr. Huang"], 
    correctIndex: 1, category: "shows_movies", difficulty: "hard" },
  { question: "What's the name of the skyscraper in Die Hard?",
    options: ["Empire State Building", "Willis Tower", "Fox Plaza", "Nakatomi Plaza"],
    correctIndex: 3, category: "shows_movies", difficulty: "hard" },
  { question: "What flavor of Pop-Tarts does Buddy the Elf use in his spaghetti?",
    options: ["Chocolate", "Strawberry", "Cookies & Cream", "S'mores"],
    correctIndex: 0, category: "shows_movies", difficulty: "hard" },
  { question: "How many suns does Luke's home planet of Tatooine have in Star Wars?",
    options: ["0", "1", "2", "3"],
    correctIndex: 2, category: "shows_movies", difficulty: "hard" },


  // ------------------------------------------------------
  // Geography and History  (15 questions per difficulty)
  // EASY
  { question: "What is the capital of France?", 
    options: ["Berlin", "Madrid", "Paris", "Rome"], 
    correctIndex: 2, category: "geography_history", difficulty: "easy" },
  { question: "Which continent has the most countries?", 
    options: ["Africa", "Asia", "Europe", "South America"], 
    correctIndex: 0, category: "geography_history", difficulty: "easy" },
  { question: "Who was the first President of the United States?", 
    options: ["George Washington", "John Adams", "Thomas Jefferson", "James Madison"], 
    correctIndex: 0, category: "geography_history", difficulty: "easy" },
  { question: "Which ancient civilization built the pyramids?", 
    options: ["Egyptians", "Romans", "Greeks", "Mayans"], 
    correctIndex: 0, category: "geography_history", difficulty: "easy" },
  { question: "Which river runs through Egypt?", 
    options: ["Nile", "Amazon", "Mississippi", "Yangtze"], 
    correctIndex: 0, category: "geography_history", difficulty: "easy" },
  { question: "Who discovered America?", 
    options: ["Christopher Columbus","Leif Erikson","Ferdinand Magellan","Amerigo Vespucci"], 
    correctIndex: 0, category: "geography_history", difficulty: "easy" },
  { question: "What is the capital of Japan?", 
    options: ["Seoul","Beijing","Tokyo","Bangkok"], 
    correctIndex: 2, category: "geography_history", difficulty: "easy" },
  { question: "Which US state is known as the 'Sunshine State'?", 
    options: ["California","Florida","Texas","Arizona"], 
    correctIndex: 1, category: "geography_history", difficulty: "easy" },
  { question: "Which country is famous for the Colosseum?", 
    options: ["Greece","Italy","Spain","Egypt"], 
    correctIndex: 1, category: "geography_history", difficulty: "easy" },
  { question: "When did the US declare independence?", 
    options: ["1712", "1776", "1804", "1812"], 
    correctIndex: 1, category: "geography_history", difficulty: "easy" },
  { question: "Which war ended in 1945?", 
    options: ["WWI", "WWII", "Vietnam War", "Korean War"], 
    correctIndex: 1, category: "geography_history", difficulty: "easy" },
  { question: "What is the largest ocean on Earth?",
    options: ["Atlantic", "Indian", "Arctic", "Pacific"],
    correctIndex: 3, category: "geography_history", difficulty: "easy" },
  { question: "On which continent is the Amazon rainforest located?",
    options: ["Africa", "Asia", "South America", "Australia"],
    correctIndex: 2, category: "geography_history", difficulty: "easy" },
  { question: "What is the tallest mountain in the world?",
    options: ["K2", "Mount Everest", "Mont Blanc", "Kilimanjaro"],
    correctIndex: 1, category: "geography_history", difficulty: "easy" },
  { question: "What is the name of the ship that sank after hitting an iceberg in 1912?",
    options: ["Lusitania", "Britannic", "Titanic", "Olympia"],
    correctIndex: 2, category: "geography_history", difficulty: "easy" },

  // MEDIUM
  { question: "What is the capital of Finland?", 
    options: ["Oslo", "Stockholm", "Copenhagen", "Helsinki"], 
    correctIndex: 3, category: "geography_history", difficulty: "medium" },
  { question: "What is the capital of Australia?", 
    options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], 
    correctIndex: 2, category: "geography_history", difficulty: "medium" },
  { question: "Which city is the capital of Canada?", 
    options: ["Toronto","Vancouver","Ottawa","Montreal"], 
    correctIndex: 2, category: "geography_history", difficulty: "medium" },
  { question: "Which country was known as Persia?", 
    options: ["Iraq","Iran","Turkey","Afghanistan"], 
    correctIndex: 1, category: "geography_history", difficulty: "medium" },
  { question: "Which empire was ruled by Genghis Khan?", 
    options: ["Mongol","Ottoman","Roman","Persian"], 
    correctIndex: 0, category: "geography_history", difficulty: "medium" },
  { question: "What year did World War I begin?",
    options: ["1912", "1914", "1916", "1918"],
    correctIndex: 1, category: "geography_history", difficulty: "medium" },
  { question: "Which country gifted the Statue of Liberty to the United States?",
    options: ["England", "Spain", "France", "Italy"],
    correctIndex: 2, category: "geography_history", difficulty: "medium" },
  { question: "Which US president signed the Emancipation Proclamation?",
    options: ["Ulysses Grant", "Andrew Jackson", "Abraham Lincoln", "James Buchanan"],
    correctIndex: 2, category: "geography_history", difficulty: "medium" },
  { question: "Who was the first woman to win a Nobel Prize?",
    options: ["Rosalind Franklin", "Marie Curie", "Ada Lovelace", "Florence Nightingale"],
    correctIndex: 1, category: "geography_history", difficulty: "medium" },
  { question: "Which country has the most natural lakes in the world?",
    options: ["Russia", "USA", "Finland", "Canada"],
    correctIndex: 3, category: "geography_history", difficulty: "medium" },
  { question: "What was the name of the first artificial satellite launched into space?",
    options: ["Apollo", "Sputnik", "Vostok", "Explorer"],
    correctIndex: 1, category: "geography_history", difficulty: "medium" },
  { question: "Which country does the Panama Canal connect the Atlantic and Pacific through?",
    options: ["Mexico", "Colombia", "Nicaragua", "Panama"],
    correctIndex: 3, category: "geography_history", difficulty: "medium" },
  { question: "What is the capital of South Korea?",
    options: ["Busan", "Incheon", "Seoul", "Daegu"],
    correctIndex: 2, category: "geography_history", difficulty: "medium" },
  { question: "What is the largest non-continental island in the world?",
    options: ["Ireland", "Greenland", "Madagascar", "New Guinea"],
    correctIndex: 1, category: "geography_history", difficulty: "medium" },
  { question: "What was the name of the first moon landing mission?",
    options: ["Apollo 9", "Apollo 10", "Apollo 11", "Apollo 12"],
    correctIndex: 2, category: "geography_history", difficulty: "medium" },


  // HARD
  { question: "How many countries are in the European Union (EU) as of 2024?", 
    options: ["28", "30", "32","27"], 
    correctIndex: 3, category: "geography_history", difficulty: "hard" },
  { question: "What year did the Berlin Wall fall?", 
    options: ["1987","1989","1991","1993"], 
    correctIndex: 1, category: "geography_history", difficulty: "hard" },
  { question: "Which country hosted the 2016 Summer Olympics?", 
    options: ["China","Brazil","UK","Russia"], 
    correctIndex: 1, category: "geography_history", difficulty: "hard" },
  { question: "Who was known as the Maid of Orléans?", 
    options: ["Joan of Arc","Marie Curie","Queen Elizabeth","Catherine the Great"], 
    correctIndex: 0, category: "geography_history", difficulty: "hard" },
  { question: "In what year did the Ottoman Empire officially collapse?",
    options: ["1918", "1920", "1922", "1924"],
    correctIndex: 2, category: "geography_history", difficulty: "hard" },
  { question: "What was the name of the first European explorer to reach India by sea?",
    options: ["Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama", "Bartolomeu Dias"],
    correctIndex: 2, category: "geography_history", difficulty: "hard" },
  { question: "Which country has the most time zones?",
    options: ["Russia", "USA", "China", "France"],
    correctIndex: 3, category: "geography_history", difficulty: "hard" },
  { question: "Which battle is considered Napoleon's final defeat?",
    options: ["Battle of Leipzig", "Battle of Waterloo", "Battle of Austerlitz", "Battle of Borodino"],
    correctIndex: 1, category: "geography_history", difficulty: "hard" },
  { question: "What year did the Soviet Union officially dissolve?",
    options: ["1989", "1990", "1991", "1992"],
    correctIndex: 2, category: "geography_history", difficulty: "hard" },
  { question: "Which empire was the largest contiguous land empire in history?",
    options: ["Mongol Empire", "British Empire", "Roman Empire", "Russian Empire"],
    correctIndex: 0, category: "geography_history", difficulty: "hard" },
  { question: "Which country was the first to grant women the right to vote?",
    options: ["USA", "UK", "Australia", "New Zealand"],
    correctIndex: 3, category: "geography_history", difficulty: "hard" },
  { question: "Which ancient wonder of the world was located in Alexandria, Egypt?",
    options: ["The Colossus of Rhodes", "The Lighthouse of Alexandria", "The Hanging Gardens", "The Temple of Artemis"],
    correctIndex: 1, category: "geography_history", difficulty: "hard" },
  { question: "What is the only sea in the world without a land boundary?",
    options: ["Sargasso Sea", "Labrador Sea", "Arabian Sea", "Scotia Sea"],
    correctIndex: 0, category: "geography_history", difficulty: "hard" },
  { question: "What country has the most pyramids in the world?",
    options: ["Mexico", "Egypt", "Peru", "Sudan"],
    correctIndex: 3, category: "geography_history", difficulty: "hard" },
  { question: "Which country has the most islands?",
    options: ["Sweden", "Finland", "Norway", "Canada"],
    correctIndex: 0, category: "geography_history", difficulty: "hard" },


// ------------------------------------------------------
// POP CULTURE (15 questions per difficulty)
// EASY
  { question: "Which artist released the hit song 'Shape of You'?", 
    options: ["Sabrina Carpenter", "Drake", "Ed Sheeran", "Bruno Mars"], 
    correctIndex: 2, category: "pop_culture", difficulty: "easy" },
  { question: "Which social media platform was formerly known for its bird logo?", 
    options: ["Snapchat", "Twitter", "Facebook", "TikTok"], 
    correctIndex: 1, category: "pop_culture", difficulty: "easy" },
  { question: "Which video game features Mario and Luigi?", 
    options: ["Mario Kart", "Zelda", "Sonic", "Fortnite"], 
    correctIndex: 0, category: "pop_culture", difficulty: "easy" },
  { question: "Which artist is known as the 'King of Pop'?", 
    options: ["Elvis Presley","Michael Jackson","Prince","Justin Timberlake"], 
    correctIndex: 1, category: "pop_culture", difficulty: "easy" },
  { question: "Which movie features a character named Shrek?", 
    options: ["Ice Age","Madagascar","Kung Fu Panda","Shrek"], 
    correctIndex: 3, category: "pop_culture", difficulty: "easy" },
  { question: "Which singer is famous for 'Rolling in the Deep'?", 
    options: ["Adele","Beyonce","Rihanna","Katy Perry"], 
    correctIndex: 0, category: "pop_culture", difficulty: "easy" },
  { question: "Which social media platform is known for short video clips?", 
    options: ["TikTok","Instagram","Snapchat","Facebook"], 
    correctIndex: 0, category: "pop_culture", difficulty: "easy" },
  { question: "Which singer is known for the album 'Thriller'?",
    options: ["Prince", "Michael Jackson", "David Bowie", "Elton John"],
    correctIndex: 1, category: "pop_culture", difficulty: "easy" },
  { question: "Which movie series features a character named Katniss Everdeen?", 
    options: ["Divergent","The Hunger Games","Twilight","Maze Runner"], 
    correctIndex: 1, category: "pop_culture", difficulty: "easy" },
  { question: "Which superhero is played by Robert Downey Jr.?", 
    options: ["Iron Man","Batman","Spider-Man","Captain America"], 
    correctIndex: 0, category: "pop_culture", difficulty: "easy" },
  { question: "Which singer released 'Bad Guy' in 2019?", 
    options: ["Dua Lipa","Ariana Grande","Billie Eilish","Taylor Swift"], 
    correctIndex: 2, category: "pop_culture", difficulty: "easy" },
  { question: "Which singer is known as 'Queen Bey'?",
    options: ["Rihanna", "Beyoncé", "Taylor Swift", "Adele"],
    correctIndex: 1, category: "pop_culture", difficulty: "easy" },
  { question: "Which app lets users send disappearing photo messages?",
    options: ["Twitter", "Pinterest", "Reddit", "Snapchat"],
    correctIndex: 3, category: "pop_culture", difficulty: "easy" },
  { question: "Which boy band sang 'I Want It That Way'?",
    options: ["NSYNC", "One Direction", "Backstreet Boys", "Jonas Brothers"],
    correctIndex: 2, category: "pop_culture", difficulty: "easy" },
  { question: "What is the name of Batman's home city?",
    options: ["Metropolis", "Star City", "Gotham", "Central City"],
    correctIndex: 2, category: "pop_culture", difficulty: "easy" },


// MEDIUM
  { question: "Which streaming platform has 'Stranger Things'?", 
    options: ["Hulu", "Disney+", "HBO Max", "Netflix"], 
    correctIndex: 3, category: "pop_culture", difficulty: "medium" },
  { question: "Who is the creator of the Star Wars franchise?", 
    options: ["J.J. Abrams","Steven Spielberg","James Cameron","George Lucas"], 
    correctIndex: 3, category: "pop_culture", difficulty: "medium" },
  { question: "Which pop star performed at the Super Bowl halftime show in 2020?", 
    options: ["Beyonce","Shakira & JLo","Lady Gaga","Bruno Mars"], 
    correctIndex: 1, category: "pop_culture", difficulty: "medium" },
  { question: "Which video game features Link as the main character?", 
    options: ["The Legend of Zelda","Mario Kart","Sonic","Fortnite"], 
    correctIndex: 0, category: "pop_culture", difficulty: "medium" },
  { question: "Which artist had a 2023 record-breaking world tour called 'Renaissance'?",
    options: ["Taylor Swift", "Beyoncé", "Adele", "Rihanna"],
    correctIndex: 1, category: "pop_culture", difficulty: "medium" },
  { question: "What is the name of the fictional kingdom in Frozen?",
    options: ["Narnia", "Arendelle", "Agrabah", "Genovia"],
    correctIndex: 1, category: "pop_culture", difficulty: "medium" },
  { question: "Which rapper is known as 'Slim Shady'?",
    options: ["Jay-Z", "Kanye West", "Eminem", "Lil Wayne"],
    correctIndex: 2, category: "pop_culture", difficulty: "medium" },
  { question: "Which show popularized the phrase 'Winter is Coming'?",
    options: ["Vikings", "The Witcher", "Lord of the Rings", "Game of Thrones"],
    correctIndex: 3, category: "pop_culture", difficulty: "medium" },
  { question: "Which artist released the album '1989'?",
    options: ["Katy Perry", "Adele", "Taylor Swift", "Dua Lipa"],
    correctIndex: 2, category: "pop_culture", difficulty: "medium" },
  { question: "Which video game franchise features a character named Master Chief?",
    options: ["Call of Duty", "Destiny", "Halo", "Gears of War"],
    correctIndex: 2, category: "pop_culture", difficulty: "medium" },
  { question: "Which two rappers are known for their longterm beef?",
    options: ["Megan Thee Stallion and Cardi B", "Eminem and Mac Miller", "Lil Tecca and Lil Jon", "Cardi B and Nicki Minaj"],
    correctIndex: 3, category: "pop_culture", difficulty: "medium" },
  { question: "Who is the protagonist of the video game Resident Evil 2?",
    options: ["Chris Redfield", "Leon Kennedy", "Arthur Morgan", "Lara Croft"],
    correctIndex: 1, category: "pop_culture", difficulty: "medium" },
  { question: "Which movie is famously celebrated for its soundtrack?",
    options: ["Divergent", "Titanic", "Interstellar", "Jumanji"],
    correctIndex: 2, category: "pop_culture", difficulty: "medium" },
  { question: "Who wrote the Twilight book series?",
    options: ["Sarah J Maas", "Stephanie Meyer", "Mary Shelley", "James Dashner"],
    correctIndex: 1, category: "pop_culture", difficulty: "medium" },
  { question: "Which tech entrepreneur named his son X Æ A-12?",
    options: ["Elon Musk", "Jeff Bezos", "Mark Zuckerberg", "Bill Gates"],
    correctIndex: 0, category: "pop_culture", difficulty: "medium" },

// HARD 
  { question: "Which celebrity hosted SNL in 2023?", 
    options: ["Billie Eilish", "Tom Holland", "Zendaya", "Elon Musk"], 
    correctIndex: 2, category: "pop_culture", difficulty: "hard" },
  { question: "Which film won Best Picture at the 2020 Oscars?", 
    options: ["1917","Joker","Parasite","Ford v Ferrari"], 
    correctIndex: 2, category: "pop_culture", difficulty: "hard" },
  { question: "Which artist holds the record for the most Grammy wins ever?",
    options: ["Michael Jackson", "Taylor Swift", "Beyoncé", "Georg Solti"],
    correctIndex: 3, category: "pop_culture", difficulty: "hard" },
  { question: "What was the best-selling video game of 2023?",
    options: ["Hogwarts Legacy", "Zelda: Tears of the Kingdom", "Mortal Kombat 1", "Spider-Man 2"],
    correctIndex: 1, category: "pop_culture", difficulty: "hard" },
  { question: "What year did Instagram launch?",
    options: ["2008", "2009", "2010", "2011"],
    correctIndex: 2, category: "pop_culture", difficulty: "hard" },
  { question: "Which movie won the first ever Academy Award for Best Animated Feature in 2002?",
    options: ["Monsters Inc", "Ice Age", "Shrek", "Spirit"],
    correctIndex: 2, category: "pop_culture", difficulty: "hard" },
  { question: "How many Super Bowl rings does Tom Brady have?",
    options: ["6", "7", "8", "9"],
    correctIndex: 1, category: "pop_culture", difficulty: "hard" },
  { question: "In 2020, Netflix aired a reality show that required participants to remain celibate. What was it called?",
    options: ["Love Island", "Love is Blind", "Single's Inferno", "Too Hot to Handle"],
    correctIndex: 3, category: "pop_culture", difficulty: "hard" },
  { question: "What year did Keeping Up with the Kardashians first premiere?",
    options: ["2006", "2007", "2008", "2009"],
    correctIndex: 1, category: "pop_culture", difficulty: "hard" },
  { question: "Britney Spears, Christina Aguilera, and Justin Timberlake all got their start on which TV show?",
    options: ["The Mickey Mouse Club", "Boy Meets World", "Even Stevens", "Lizzie McGuire"],
    correctIndex: 0, category: "pop_culture", difficulty: "hard" },
  { question: "Which rapper is BFFs with Martha Stewart?",
    options: ["Snoop Dogg", "Dr. Dre", "Nas", "Jay-Z"],
    correctIndex: 0, category: "pop_culture", difficulty: "hard" },
  { question: "What was the first music video played on MTV?",
    options: ["Do Ya Think I'm Sexy?", "Iron Maiden", "In The Air Tonight", "Video Killed The Radio Star"],
    correctIndex: 3, category: "pop_culture", difficulty: "hard" },
  { question: "Who was the first person to win on Survivor?",
    options: ["Ethan Zohn", "Tina Wesson", "Richard Hatch", "Tony Vlachos"],
    correctIndex: 2, category: "pop_culture", difficulty: "hard" },
  { question: "How many different actors have played Batman onscreen?",
    options: ["10", "11", "12", "13"],
    correctIndex: 1, category: "pop_culture", difficulty: "hard" },
  { question: "What is the name of the green crystal that appears in The Sims franchise?",
    options: ["Plumbob", "Simoleon", "WooHoo", "Doubloon"],
    correctIndex: 0, category: "pop_culture", difficulty: "hard" }
];